/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apkcore_tabstripdemo_ndk_MessageJni */

#ifndef _Included_com_apkcore_tabstripdemo_ndk_MessageJni
#define _Included_com_apkcore_tabstripdemo_ndk_MessageJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apkcore_tabstripdemo_ndk_MessageJni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apkcore_tabstripdemo_ndk_MessageJni_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
